### ISSUE TITLE
(Question) UV Index

### ISSUE THREAD

**Issue by Ttech** [schizobovine/VEML6075#1]
Hi,
Couldn't find a way to contact you otherwise - but I was hoping you'd be willing to answer a few questions regarding UV Index. I currently have a VEML6070 and I've had a lot of trouble calculating UV Index values based off the Vishay datasheets. What did you do to calculate and get the accuracy of this sensor? Or is this library usable for the 6070?

**Comment by schizobovine** [comment]
its not usable for the 6070 as it doesn't have a uvb sensor in it.

i had similar trouble with the calculations, though, and was getting rather
nonsensical readings. i gathered some data from a few other sensors to try
to calibrate it a bit better but got bogged down in other projects.

**Comment by bonjour81** [comment]
Hello! 
I guess you may know about that but on vishay website, each of the uv sensor (veml6070 and 75) comes with a pretty good application note in addition to the datasheet. 
The application note gives a lot of information.

**Comment by schizobovine** [comment]
Yeah, the library attempts to implement the algorithm in the datasheet, but as observed in issue #3, it sometimes gives negative UV index readings (which is nonsensical). I've not gone back to double-check my work, however--I'd been collecting data from a few sensors to try to do some backwards cross checking on the constants provided in the datasheet.

**Comment by schizobovine** [comment]
Going to close this, as I believe Adafruit has a VEML6070 driver available (or at least they have a breakout, and I've not heard of them releasing many breakouts without a library).
