### ISSUE TITLE
selectable I2C Pins under esp8266

### ISSUE THREAD

**Issue by coelner** [schizobovine/VEML6075#2]
A simple patch to get this library working.
[veml6075.patch.txt](https://github.com/schizobovine/VEML6075/files/984329/veml6075.patch.txt)

**Comment by schizobovine** [comment]
Good feature to ask for, though I'm not sure if adding the i2c address pins in the begin() function is the right place for it. Typically I see sketches call ```Wire.begin()``` in ```setup()```. I think it's generally safe to call ```Wire.begin()``` but I'm not 100% sure?

I would rather the library caller handle setup of i2c, especially if it's finicky depending on device type, as that makes the library less universal.

Can you point me to other libraries where they're using this convention? I may just be a complete noob here.

**Comment by coelner** [comment]
I took it from here: https://github.com/finitespace/BME280/blob/master/src/BME280I2C.h

Usually you call Wire.begin() without any parameter, because the atmel have got hard defined i2c pins. With the ESP8266 (https://esp8266.github.io/Arduino/versions/2.3.0/doc/libraries.html#i2c-wire-library) (and other SoC) you can select these pins and bitbang i2c over software. In the case you select two different i2c bus master you need to define separately these pins. (See here: https://github.com/todbot/SoftI2CMaster)

**Comment by coelner** [comment]
It's a bit tricky here. there is a discussion about how to solve this issue. normally there is Wire.begin(SDA,SCL) at the setup() and you are not allowed to use this method in a library. but most of the libraries do this anyway. 
you could declare the Initialize() as public and remove the Wire.begin() call to avoid this. Otherwise you need to integrate the passthrough of SDA and SCL.
https://github.com/esp8266/Arduino/issues/2607
https://github.com/esp8266/Arduino/issues/2774

**Comment by schizobovine** [comment]
I've updated the code to take the Wire bus object as a parameter (copied from the Adafruit implementation for this same sensor), which defaults to the "Wire" object it was using before. Hopefully this handles your use case as well as others (using alternate i2c buses on the Teensy, e.g.).
