### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by ZbynekT** [schizobovine/VEML6075#3]
High! I've been testing these chips and your library with UV protective film and on the output I started getting negative values of UV when film was over the sensor.
Do you have any explanation for it, please?

**Comment by schizobovine** [comment]
No, I've gotten the same thing. I thought I implemented the algorithm from the datasheet but the answers were in disagreement with other sensors.

I don't *think* it's overflowing, but that could be a contribution to it?

Sadly I haven't had much time to play around with the code in a bit.

**Comment by ZbynekT** [comment]
Hi. I tried to contact the manufacturer with reference to your code and odd results, but they replied promptly that they don't support 3rd party code. Maybe if you confront them with your application and output, they will be more open and helpful.
Contact person was Sander, Georg <Georg.Sander@vishay.com>
They have send me this attached documents. I'm not sure if both are publicly accessible.
[DESIGNINGVEML6075_84339_20161125.pdf](https://github.com/schizobovine/VEML6075/files/1035124/DESIGNINGVEML6075_84339_20161125.pdf)
[VEML6075_84304_20160519.pdf](https://github.com/schizobovine/VEML6075/files/1035123/VEML6075_84304_20160519.pdf)

**Comment by schizobovine** [comment]
Looks like I was double subtracting out the IR compensation, from #4. Can you check to see if that fixes the issue for you?

**Comment by ZbynekT** [comment]
Yes, I will. Unfortunately, I'm physically out of the project know. The closest time will be in the middle of July. I'll post here then for sure. Thanks for the improvements, guys!

**Comment by schizobovine** [comment]
Latest code push restricts values to positive only during the compensation calculations. Hopefully this should fix this bug for folks. Please let me know if you're still seeing the issue after updating.
