### ISSUE TITLE
wrong formular in getUVA and getUVB

### ISSUE THREAD

**Issue by feuerwolf** [schizobovine/VEML6075#5]
float VEML6075::getUVA() {
  float comp_vis = this->raw_vis - this->raw_dark;
  float comp_ir  = this->raw_ir  - this->raw_dark;
  float comp_uva = this->raw_uva - this->raw_dark;
  // false formular:
  comp_uva -= (VEML6075_UVI_UVA_VIS_COEFF * comp_vis) - (VEML6075_UVI_UVA_IR_COEFF * comp_ir);
  // it is supposed to be UVAcalc = UVA - a x UVcomp1 - b x UVcomp2
 // App Note 84339 ; page 6/22
  return comp_uva;
}

**Comment by coelner** [comment]
I'm not sure where you see an error. Did you oversee the `-=` ?

**Comment by feuerwolf** [comment]
I will check again these days and let you know

**Comment by schizobovine** [comment]
I believe this should be fixed now; please reopen if you think the formula in the latest update is still incorrect. I had to stray a little from the datasheet to keep the values from dipping negative (see issue #3).
