### ISSUE TITLE
wrong a,b,c,d, coeff! wrong UVAresp, UVBresp

### ISSUE THREAD

**Issue by feuerwolf** [schizobovine/VEML6075#6]
appl Note 84339 Page 7/22 and 15/22

**Comment by feuerwolf** [comment]
looks like there coefficients has changed in App Note releases

**Comment by coelner** [comment]
Yeah, the push of the first entry in the source was in jun '16, the changed the datasheet in nov 16.

**Comment by schizobovine** [comment]
Updated coefficients to newer versions of coefficients from the 2018-06-05 version of the application note.
